# Generated by Django 4.0.1 on 2022-01-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('chat_photo', models.BinaryField()),
                ('view_participants', models.BooleanField()),
                ('participants_count', models.BigIntegerField()),
                ('online_count', models.BigIntegerField()),
                ('linked_chat_id', models.BigIntegerField()),
            ],
        ),
    ]
