# Generated by Django 4.0.1 on 2022-01-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelinfo',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
