# Generated by Django 4.0.1 on 2022-01-31 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel_info', '0002_alter_channelinfo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelinfo',
            old_name='about',
            new_name='json',
        ),
        migrations.RemoveField(
            model_name='channelinfo',
            name='chat_photo',
        ),
        migrations.RemoveField(
            model_name='channelinfo',
            name='linked_chat_id',
        ),
        migrations.RemoveField(
            model_name='channelinfo',
            name='online_count',
        ),
        migrations.RemoveField(
            model_name='channelinfo',
            name='participants_count',
        ),
        migrations.RemoveField(
            model_name='channelinfo',
            name='view_participants',
        ),
    ]
