# Generated by Django 4.0.1 on 2022-01-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_info', '0004_alter_channelinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelinfo',
            name='json',
            field=models.JSONField(),
        ),
    ]
